# Generated by Django 3.2.15 on 2022-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=30)),
                ('ve', models.CharField(max_length=5)),
                ('vo', models.CharField(max_length=5)),
                ('oe', models.CharField(max_length=5)),
                ('oo', models.CharField(max_length=5)),
                ('vt', models.CharField(max_length=5)),
                ('ot', models.CharField(max_length=5)),
                ('tt', models.CharField(max_length=5)),
            ],
        ),
    ]
